/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.awt.*;

/**
 *
 * @author Tarles
 */
public class Principal extends javax.swing.JFrame {

   /**
    * Creates new form Principal
    */
   private SerialTest serialteste;

   public Principal() {
      initComponents();
   }

   public Principal(SerialTest serialt) {
      serialteste = serialt;
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jTextField1 = new javax.swing.JTextField();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      jButton4 = new javax.swing.JButton();
      jButton5 = new javax.swing.JButton();
      jButton6 = new javax.swing.JButton();
      jButton7 = new javax.swing.JButton();
      jButton8 = new javax.swing.JButton();
      jButton9 = new javax.swing.JButton();
      jButton10 = new javax.swing.JButton();
      jButton12 = new javax.swing.JButton();
      jButton13 = new javax.swing.JButton();
      jButton14 = new javax.swing.JButton();
      jButton15 = new javax.swing.JButton();
      jButton16 = new javax.swing.JButton();
      jButton17 = new javax.swing.JButton();
      jButton18 = new javax.swing.JButton();
      jButton11 = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jButton19 = new javax.swing.JButton();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
      setTitle("WARM UP");
      setIconImage(new javax.swing.ImageIcon("icone.png").getImage());
      setResizable(false);
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowClosing(java.awt.event.WindowEvent evt) {
            formWindowClosing(evt);
         }
      });

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("HyperTerminal - Warm UP"));

      jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            jTextField1KeyPressed(evt);
         }
      });

      jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton1.setText("1");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton2.setText("2");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
         }
      });

      jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton3.setText("3");
      jButton3.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
         }
      });

      jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton4.setText("4");
      jButton4.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
         }
      });

      jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton5.setText("5");
      jButton5.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
         }
      });

      jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton6.setText("6");
      jButton6.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
         }
      });

      jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton7.setText("7");
      jButton7.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton7ActionPerformed(evt);
         }
      });

      jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton8.setText("8");
      jButton8.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton8ActionPerformed(evt);
         }
      });

      jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton9.setText("9");
      jButton9.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton9ActionPerformed(evt);
         }
      });

      jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton10.setText("0");
      jButton10.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton10ActionPerformed(evt);
         }
      });

      jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton12.setText("+");
      jButton12.setEnabled(false);
      jButton12.setMaximumSize(new java.awt.Dimension(41, 25));
      jButton12.setMinimumSize(new java.awt.Dimension(41, 25));
      jButton12.setPreferredSize(new java.awt.Dimension(41, 25));
      jButton12.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton12ActionPerformed(evt);
         }
      });

      jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton13.setText("-");
      jButton13.setEnabled(false);
      jButton13.setMaximumSize(new java.awt.Dimension(41, 25));
      jButton13.setMinimumSize(new java.awt.Dimension(41, 25));
      jButton13.setPreferredSize(new java.awt.Dimension(41, 25));
      jButton13.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton13ActionPerformed(evt);
         }
      });

      jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton14.setText("*");
      jButton14.setEnabled(false);
      jButton14.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton14ActionPerformed(evt);
         }
      });

      jButton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton15.setText("/");
      jButton15.setEnabled(false);
      jButton15.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton15ActionPerformed(evt);
         }
      });

      jButton16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton16.setText("AND");
      jButton16.setEnabled(false);
      jButton16.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton16ActionPerformed(evt);
         }
      });

      jButton17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton17.setText("OR");
      jButton17.setEnabled(false);
      jButton17.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton17ActionPerformed(evt);
         }
      });

      jButton18.setBackground(new java.awt.Color(255, 153, 51));
      jButton18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton18.setText("=");
      jButton18.setEnabled(false);
      jButton18.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton18ActionPerformed(evt);
         }
      });

      jButton11.setText("Limpar");
      jButton11.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton11ActionPerformed(evt);
         }
      });

      jLabel1.setText("Problema 1");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 179, Short.MAX_VALUE)
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 88, Short.MAX_VALUE)
      );

      jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
      jLabel2.setText("OPERADOR A");
      jLabel2.setEnabled(false);

      jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
      jLabel4.setText("RESULTADO");
      jLabel4.setEnabled(false);

      jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
      jLabel3.setText("OPERADOR B");
      jLabel3.setEnabled(false);

      jButton19.setText("Sair");
      jButton19.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton19ActionPerformed(evt);
         }
      });

      jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

      jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

      jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
      jLabel7.setForeground(new java.awt.Color(255, 0, 0));

      jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
      jLabel8.setForeground(new java.awt.Color(204, 204, 204));
      jLabel8.setText("By Tarles Walker");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(115, 115, 115)
                  .addComponent(jLabel1))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(20, 20, 20)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel8)
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                           .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                           .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                           .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                 .addComponent(jButton4)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                 .addComponent(jButton5)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                 .addComponent(jButton6))
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                 .addComponent(jButton1)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                 .addComponent(jButton2)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                 .addComponent(jButton3))
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                 .addComponent(jButton7)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                 .addComponent(jButton8)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                 .addComponent(jButton9))
                              .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                           .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton16)
                                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton15)
                                    .addComponent(jButton14))
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                 .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
            .addContainerGap(30, Short.MAX_VALUE))
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(4, 4, 4)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jButton1)
                     .addComponent(jButton2)
                     .addComponent(jButton3)
                     .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jButton16))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jButton4)
                     .addComponent(jButton5)
                     .addComponent(jButton6)
                     .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jButton17))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jButton7)
                     .addComponent(jButton8)
                     .addComponent(jButton9)
                     .addComponent(jButton14))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jButton10)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jButton15)
                  .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButton11)
               .addComponent(jButton19))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel8))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 318, Short.MAX_VALUE)
         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(0, 0, Short.MAX_VALUE)))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 369, Short.MAX_VALUE)
         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(0, 0, Short.MAX_VALUE)))
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if (jTextField1.getText().trim().isEmpty()) {
         this.habilitaoperadores();
      }
      jTextField1.setText(jTextField1.getText() + "1");
   }//GEN-LAST:event_jButton1ActionPerformed

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if (jTextField1.getText().trim().isEmpty()) {
         this.habilitaoperadores();
      }
      jTextField1.setText(jTextField1.getText() + "2");
   }//GEN-LAST:event_jButton2ActionPerformed

   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      if (jTextField1.getText().trim().isEmpty()) {
         this.habilitaoperadores();
      }
      jTextField1.setText(jTextField1.getText() + "3");
   }//GEN-LAST:event_jButton3ActionPerformed

   private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      if (jTextField1.getText().trim().isEmpty()) {
         this.habilitaoperadores();
      }
      jTextField1.setText(jTextField1.getText() + "4");
   }//GEN-LAST:event_jButton4ActionPerformed

   private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      if (jTextField1.getText().trim().isEmpty()) {
         this.habilitaoperadores();
      }
      jTextField1.setText(jTextField1.getText() + "5");
   }//GEN-LAST:event_jButton5ActionPerformed

   private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      if (jTextField1.getText().trim().isEmpty()) {
         this.habilitaoperadores();
      }
      jTextField1.setText(jTextField1.getText() + "6");
   }//GEN-LAST:event_jButton6ActionPerformed

   private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      if (jTextField1.getText().trim().isEmpty()) {
         this.habilitaoperadores();
      }
      jTextField1.setText(jTextField1.getText() + "7");
   }//GEN-LAST:event_jButton7ActionPerformed

   private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      if (jTextField1.getText().trim().isEmpty()) {
         this.habilitaoperadores();
      }
      jTextField1.setText(jTextField1.getText() + "8");
   }//GEN-LAST:event_jButton8ActionPerformed

   private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      if (jTextField1.getText().trim().isEmpty()) {
         this.habilitaoperadores();
      }
      jTextField1.setText(jTextField1.getText() + "9");      // TODO add your handling code here:
   }//GEN-LAST:event_jButton9ActionPerformed

   private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      if (jTextField1.getText().trim().isEmpty()) {
         this.habilitaoperadores();
      }
      jTextField1.setText(jTextField1.getText() + "0");
   }//GEN-LAST:event_jButton10ActionPerformed

   private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
      if (jTextField1.getText().indexOf("+") != -1) {
         return;
      }
      jTextField1.setText(jTextField1.getText() + "+");
      jButton18.setEnabled(true);
      jButton12.setBackground(Color.RED);

      jButton13.setEnabled(false);
      jButton14.setEnabled(false);
      jButton15.setEnabled(false);
      jButton16.setEnabled(false);
      jButton17.setEnabled(false);

   }//GEN-LAST:event_jButton12ActionPerformed

   private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
      if (jTextField1.getText().indexOf("-") != -1) {
         return;
      }
      jTextField1.setText(jTextField1.getText() + "-");
      jButton18.setEnabled(true);
      jButton13.setBackground(Color.RED);

      jButton12.setEnabled(false);
      jButton14.setEnabled(false);
      jButton15.setEnabled(false);
      jButton16.setEnabled(false);
      jButton17.setEnabled(false);
   }//GEN-LAST:event_jButton13ActionPerformed

   private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
      if (jTextField1.getText().indexOf("*") != -1) {
         return;
      }
      jTextField1.setText(jTextField1.getText() + "*");
      jButton18.setEnabled(true);
      jButton14.setBackground(Color.RED);

      jButton12.setEnabled(false);
      jButton13.setEnabled(false);
      jButton15.setEnabled(false);
      jButton16.setEnabled(false);
      jButton17.setEnabled(false);
   }//GEN-LAST:event_jButton14ActionPerformed

   private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
      if (jTextField1.getText().indexOf("/") != -1) {
         return;
      }
      jTextField1.setText(jTextField1.getText() + "/");
      jButton18.setEnabled(true);
      jButton15.setBackground(Color.RED);

      jButton12.setEnabled(false);
      jButton13.setEnabled(false);
      jButton14.setEnabled(false);
      jButton16.setEnabled(false);
      jButton17.setEnabled(false);
   }//GEN-LAST:event_jButton15ActionPerformed

   private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
      if (jTextField1.getText().indexOf("&") != -1) {
         return;
      }
      jTextField1.setText(jTextField1.getText() + "&");
      jButton18.setEnabled(true);
      jButton16.setBackground(Color.RED);

      jButton12.setEnabled(false);
      jButton13.setEnabled(false);
      jButton14.setEnabled(false);
      jButton15.setEnabled(false);
      jButton17.setEnabled(false);
   }//GEN-LAST:event_jButton16ActionPerformed

   private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
      if (jTextField1.getText().indexOf("|") != -1) {
         return;
      }
      jTextField1.setText(jTextField1.getText() + "|");
      jButton18.setEnabled(true);
      jButton17.setBackground(Color.RED);

      jButton12.setEnabled(false);
      jButton13.setEnabled(false);
      jButton14.setEnabled(false);
      jButton15.setEnabled(false);
      jButton16.setEnabled(false);
   }//GEN-LAST:event_jButton17ActionPerformed

   private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      jTextField1.setText("");
      jPanel2.repaint();
      jLabel2.setEnabled(false);
      jLabel5.setText("");
      jLabel3.setEnabled(false);
      jLabel6.setText("");
      jLabel4.setEnabled(false);
      jLabel7.setText("");
      jButton12.setEnabled(false);
      jButton12.setBackground(null);
      jButton13.setEnabled(false);
      jButton13.setBackground(null);
      jButton14.setEnabled(false);
      jButton14.setBackground(null);
      jButton15.setEnabled(false);
      jButton15.setBackground(null);
      jButton16.setEnabled(false);
      jButton16.setBackground(null);
      jButton17.setEnabled(false);
      jButton17.setBackground(null);
      jButton18.setEnabled(false);

   }//GEN-LAST:event_jButton11ActionPerformed

   private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
      jLabel2.setEnabled(true);
      jLabel3.setEnabled(true);
      jLabel4.setEnabled(true);
      this.listabintela();
   }//GEN-LAST:event_jButton18ActionPerformed

   private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
      if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
         jLabel2.setEnabled(true);
         jLabel3.setEnabled(true);
         jLabel4.setEnabled(true);
         this.listabintela();
      }
   }//GEN-LAST:event_jTextField1KeyPressed

   private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
      if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja sair") == javax.swing.JOptionPane.OK_OPTION) {
         if (serialteste != null) {
            serialteste.close();
         }
         java.lang.System.exit(0);
      }
   }//GEN-LAST:event_jButton19ActionPerformed

   private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja sair") == javax.swing.JOptionPane.OK_OPTION) {
         if (serialteste != null) {
            serialteste.close();
         }
         java.lang.System.exit(0);
      }
   }//GEN-LAST:event_formWindowClosing

   /**
    * @param args the command line arguments
    */
   /* public static void main(String args[]) {
    new Principal().setVisible(true);
    }
    */
   private void habilitaoperadores() {
      jButton12.setEnabled(true);
      jButton13.setEnabled(true);
      jButton14.setEnabled(true);
      jButton15.setEnabled(true);
      jButton16.setEnabled(true);
      jButton17.setEnabled(true);
   }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton10;
   private javax.swing.JButton jButton11;
   private javax.swing.JButton jButton12;
   private javax.swing.JButton jButton13;
   private javax.swing.JButton jButton14;
   private javax.swing.JButton jButton15;
   private javax.swing.JButton jButton16;
   private javax.swing.JButton jButton17;
   private javax.swing.JButton jButton18;
   private javax.swing.JButton jButton19;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton5;
   private javax.swing.JButton jButton6;
   private javax.swing.JButton jButton7;
   private javax.swing.JButton jButton8;
   private javax.swing.JButton jButton9;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JTextField jTextField1;
   // End of variables declaration//GEN-END:variables

   private void listabintela() {

      String text = jTextField1.getText().trim();
      String[] ops;
      int resultado = 0;
      if (text.indexOf("+") != -1) { //Se for diferente de -1 é pq existe.
         ops = text.split(java.util.regex.Pattern.quote("+"));
         if (ops.length == 2 && !ops[0].equals("")) {
            resultado = this.somar(Integer.parseInt(ops[0]), Integer.parseInt(ops[1]));
            this.comunica(ops[0], ops[1], "+");
         }
      } else if (text.indexOf("-") != -1) {
         ops = text.split(java.util.regex.Pattern.quote("-"));
         if (ops.length == 2 && !ops[0].equals("")) {
            resultado = this.diminuir(Integer.parseInt(ops[0]), Integer.parseInt(ops[1]));
            this.comunica(ops[0], ops[1], "+");
         }
      } else if (text.indexOf("*") != -1) {
         ops = text.split(java.util.regex.Pattern.quote("*"));
         if (ops.length == 2 && !ops[0].equals("")) {
            resultado = this.multiplicar(Integer.parseInt(ops[0]), Integer.parseInt(ops[1]));
            this.comunica(ops[0], ops[1], "*");
         }
      } else if (text.indexOf("/") != -1) {
         ops = text.split(java.util.regex.Pattern.quote("/"));
         if (ops.length == 2 && !ops[0].equals("")) {
            if (Integer.parseInt(ops[1]) == 0) {
               javax.swing.JOptionPane.showMessageDialog(null, "Não se pode efetuar divisão por zero!", "Atenção!", 2);
               return;
            }
            resultado = this.dividir(Integer.parseInt(ops[0]), Integer.parseInt(ops[1]));
            this.comunica(ops[0], ops[1], "/");
         }
      } else if (text.indexOf("&") != -1) {
         ops = text.split(java.util.regex.Pattern.quote("&"));
         if (ops.length == 2 && !ops[0].equals("")) {
            resultado = this.and(Integer.parseInt(ops[0]), Integer.parseInt(ops[1]));
            this.comunica(ops[0], ops[1], "&");
         }
      } else if (text.indexOf("|") != -1) {
         ops = text.split(java.util.regex.Pattern.quote("|"));
         if (ops.length == 2 && !ops[0].equals("")) {
            resultado = this.or(Integer.parseInt(ops[0]), Integer.parseInt(ops[1]));
            this.comunica(ops[0], ops[1], "|");
         }
      } else {
         javax.swing.JOptionPane.showMessageDialog(null, "Escolha ou Digite o Segundo Operando!", "Atenção!", 2);
         return;
      }
      if (resultado > 511) {
         /**
          * *************VERIFICAR DEPOIS***************
          */
      }
      if (ops.length > 2) {
         javax.swing.JOptionPane.showMessageDialog(null, "Retifique! Só poderá efetuar uma operação", "Atenção!", 2);
         return;
      }
      if (ops.length == 1) {
         javax.swing.JOptionPane.showMessageDialog(null, "Digite o próximo Operando!", "Atenção!", 2);
         return;
      }
      if (ops.length == 0 || ops[0].equals("")) {
         javax.swing.JOptionPane.showMessageDialog(null, "Verifique sua operação!", "Atenção!", 2);
         return;
      }
      String bin1 = Integer.toString(Integer.parseInt(ops[0]), 2);
      String bin2 = Integer.toString(Integer.parseInt(ops[1]), 2);
      String result = Integer.toString(resultado, 2);
      if (bin1.length() > 8 || bin2.length() > 8) {
         javax.swing.JOptionPane.showMessageDialog(null, "Retifique! O Operando deve estar entre 0 e 255!", "Atenção!", 2);
         return;
      }
      //preencher operadorandos e resultado
      jLabel5.setText(ops[0]);
      jLabel6.setText(ops[1]);
      if (resultado > 255) {
         jLabel7.setText("Err");
      } else {
         jLabel7.setText(Integer.toString(resultado));
      }

      String B1 = this.preenchebinario(bin1);
      String B2 = this.preenchebinario(bin2);
      String B3 = this.preenchebinario(result);

      this.printar(B1, B2, B3);

   }

   private String preenchebinario(String bin) {
      StringBuffer sb = new StringBuffer(bin);
      int j = bin.length();
      for (int i = 0; i < 8 - j; i++) {
         sb.insert(0, '0');
      }
      if (bin.length() > 9) {
         StringBuffer sbmodif = null;
         for (int k = 0; sb.length() != 9; k++) {
            sbmodif = sb.deleteCharAt(k);
         }
         return String.valueOf(sbmodif);
      }
      return String.valueOf(sb);
   }

   private int somar(int a, int b) {
      return a + b;
   }

   private int diminuir(int a, int b) {
      return a - b;
   }

   private int multiplicar(int a, int b) {
      return a * b;
   }

   private int dividir(int a, int b) {
      return a / b;
   }

   private int and(int a, int b) {
      return a & b;
   }

   private int or(int a, int b) {
      return a | b;
   }

   private void printar(String a, String b, String r) {
      jPanel2.paint(jPanel2.getGraphics());
      Graphics g = jPanel2.getGraphics();
      Color color;
      int diametro = 10;
      String vb;
      for (int x = 0; x < a.length(); x++) {
         if (a.charAt(x) == '1') {
            color = Color.red;
            vb = "1";
         } else {
            color = Color.GRAY;
            vb = "0";
         }
         ((Graphics2D) g).setColor(color);
         ((Graphics2D) g).setStroke(new BasicStroke(2));
         ((Graphics2D) g).fillOval(20 * x, 6, diametro, diametro);
         ((Graphics2D) g).setColor(Color.black);
         ((Graphics2D) g).drawOval(20 * x, 6, diametro, diametro);
         ((Graphics2D) g).drawString(vb, 21 * x, 27);
      }
      for (int x = 0; x < b.length(); x++) {
         if (b.charAt(x) == '1') {
            color = Color.red;
            vb = "1";
         } else {
            color = Color.GRAY;
            vb = "0";
         }
         ((Graphics2D) g).setColor(color);
         ((Graphics2D) g).setStroke(new BasicStroke(2));
         ((Graphics2D) g).fillOval(20 * x, 33, diametro, diametro);
         ((Graphics2D) g).setColor(Color.black);
         ((Graphics2D) g).drawOval(20 * x, 33, diametro, diametro);
         ((Graphics2D) g).drawString(vb, 21 * x, 54);
      }
      for (int x = 0; x < r.length(); x++) {
         Color colorb = Color.BLACK;
         if (r.charAt(x) == '1') {
            color = Color.red;
            vb = "1";
            if (x == 0 && r.length() >= 9) {
               color = Color.YELLOW;
               colorb = Color.RED;
            }
         } else {
            color = Color.GRAY;
            vb = "0";
         }
         ((Graphics2D) g).setColor(color);
         ((Graphics2D) g).setStroke(new BasicStroke(2));
         ((Graphics2D) g).fillOval(20 * x, 62, diametro, diametro);
         ((Graphics2D) g).setColor(colorb);
         ((Graphics2D) g).drawOval(20 * x, 62, diametro, diametro);
         ((Graphics2D) g).drawString(vb, 21 * x, 83);
      }
   }

   private void comunica(String opA, String opB, String operando) {
      /*String bin1 = Integer.toString(Integer.parseInt(opA), 2);
       * String B1 = this.preenchebinario(bin1);
       * String bin2 = Integer.toString(Integer.parseInt(opB), 2);
       * String B2 = this.preenchebinario(bin2);
       * char c = operando.charAt(0);
       * int i = (int) c;
       * String bin3 = Integer.toBinaryString(i);
       * String B3 = this.preenchebinario(bin3);
       * serialteste.escrevernaPorta(B3);
       * serialteste.escrevernaPorta(B1);
       * serialteste.escrevernaPorta(B2);*/
      // serialteste.escrevernaPorta(opA);
      byte[] bytes = new byte[3];
      bytes[0] = (byte) (operando.getBytes())[0];
      bytes[1] = (byte) Integer.parseInt(opA);
      bytes[2] = (byte) Integer.parseInt(opB);
      serialteste.escrevervetor(bytes);
   }
}
